### PR TITLE
Fix /api/v1/instance requiring authentication in whitelist mode

### LINKED ISSUE #1795: Cannot sign in while instance is in whitelist mode
Whitelist mode is another feature in Mastodon which allows an instance to cut itself off to just a few instances to prevent abuse. Pinafore doesn't login in this mode. I think this is a bug.

### PR DESCRIPTION
**Pull request by koyuawsmbrtn**
Hackily fixes #1795

### CODE REVIEW

**Comment by rgx1** [comment]
Thank you **Koyu**! Wonderful.

**Comment by nolanlawson** [comment]
Thanks for opening the issue and the PR, but I'm not sure what the issue is or how this is solving it? It looks like this PR is just hard-coding the instance URL to `mastodon.social`? How does that fix the whitelisting bug?

**Comment by koyuawsmbrtn** [comment]
> 
> 
> Thanks for opening the issue and the PR, but I'm not sure what the issue is or how this is solving it? It looks like this PR is just hard-coding the instance URL to `mastodon.social`? How does that fix the whitelisting bug?

I didn't know how to remove the `/api/v1/instance` check in general and I don't know why it's there in the first place. Removing it in general would fix the issue since even then Pinafore performs some checks against the input. Maybe someone comes up with a better idea, but completely removing it would be nice. I don't know what `get(url, null, { timeout: DEFAULT_TIMEOUT })` produces to make Pinafore happy and just try to authenticate anyway.

**Comment by nolanlawson** [comment]
@koyuawsmbrtn I see, so the whitelisting feature is that the Mastodon server will block API access _until_ you log in? So we cannot assume public access to `api/v1/instance`?

In that case I will need to re-architect Pinafore a bit, but this should be solveable. Do you have an example of a Mastodon instance with this whitelisting feature?

**Comment by koyuawsmbrtn** [comment]
> 
> 
> @koyuawsmbrtn I see, so the whitelisting feature is that the Mastodon server will block API access _until_ you log in? So we cannot assume public access to `api/v1/instance`?
> 
> In that case I will need to re-architect Pinafore a bit, but this should be solveable. Do you have an example of a Mastodon instance with this whitelisting feature?

Exactly. An example instance would be my own, koyu.space.

**Pull request closed without merging**
