### PR TITLE
Translation into Spanish

### PR DESCRIPTION
**Pull request by nvdaes**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks a lot! Just so you're aware, translations do not really work yet, unless you're willing to host Pinafore yourself: https://github.com/nolanlawson/pinafore/blob/master/docs/Internationalization.md

**Comment by nvdaes** [comment]
Thanks for your interest. The translation may take some time. If I cannot host Pinafore, maybe done by others or you may request help to host different languages, for example with donations. Let's see how thingsgo.

**Comment by nolanlawson** [comment]
Totally understandable. To be honest, I have not had the time to do translations properly, which is why it's in the state it's in. I just wanted to let you know before you put in a bunch of effort to translate the whole thing. :slightly_smiling_face:

**Comment by nvdaes** [comment]
I've finished this. If something needs to be improved, I'll try to do it when I use this seeing the whole context in real life, though I've read the comments of the different sections and they are helpful.
We'll need to remove some strings when PR #2300 is merged.

**Comment by nolanlawson** [comment]
Awesome, thanks! I don't know when/if we'll get internationalization actually working in Pinafore, but I appreciate the effort. :slightly_smiling_face:

**Comment by nvdaes** [comment]
A person mentioned that may host Pinafores translated into Spanish in a server. I know that emojis aren"t translated, but for now this is my work. BTW, for me is more accessible to use Pinafore"s emojis picker than the emojis panel on Windows while using Pinafore, with Nvda screen reader. Thank you.

Enviado desde mi iPhone

**Comment by nolanlawson** [comment]
Emojis are actually translated, `emoji-picker-element` supports it: https://github.com/nolanlawson/emoji-picker-element/#internationalization

I can't recall if Pinafore correctly hooks into this functionality though.

**Comment by nolanlawson** [comment]
Did not mean to close.

**Comment by nvdaes** [comment]
Ok, I think that emojis can be translated but that they aren"t translated yet. Thanks.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
Meant I thought emojis need to be translated. Just a spanish speaker typing fast and using present instead of past in a verb.

**Comment by nolanlawson** [comment]
Yes, this applies to the title/aria-label on emojis too. We get them from `emoji-picker-element`'s database.

**Comment by nvdaes** [comment]
Ok, if this is merged and hosted, I"ll see if translation of emojis works as expected. I did the translation on Windows without runing the linter, since I didn"t edit the file on WSL.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
I've fixed errors and translated new messages included in /src/intl/en-US.js
Now all checks pass. @nolanlawson , if you want, we canwait to see if moremessages have to be translated for the next release and then you may merge this.
We're talking in a spanish mailing list about the possibility to host Pinafore in Spanish and we'llbetesting this translation locally in dev mode.

**Comment by nolanlawson** [comment]
Here, this fixes the Spanish locale for the emoji picker: e335441d

I'm happy to merge this, please feel free to host your own Spanish version of Pinafore. Thanks for the effort!

**Review by nolanlawson — APPROVED** [review]

**Comment by nvdaes** [comment]
Thank you. Feel free to merge this when you want. If I detect some to improve, I"ll do after the next release. We"ll thinking about host this in Spanish, maybe on GitHub Pages or Vercel, so Ill inform that this is approved to see if we register a domain for this.

Enviado desde mi iPhone

**Pull request merged**
