### PR TITLE
feat: add option to hide checkmark

### PR DESCRIPTION
**Pull request by nolanlawson**
Don't take this the wrong way @NickColley; if anybody complains because we moved their cheese, I just want to have a ready-made answer. :slightly_smiling_face:

### CODE REVIEW

**Comment by NickColley** [comment]
@nolanlawson maybe hold on this and see the reaction first? We definitely can improve from the checkmarks, that'd be my preference over adding an option 👍

**Comment by nolanlawson** [comment]
OK sure. :slightly_smiling_face:

**Comment by NickColley** [comment]
Going to close this out but we can re-open if we need to consider this...

**Comment by nolanlawson** [comment]
Nobody complained so far

**Comment by nolanlawson** [comment]
Hah, I literally was trying to close this the exact same minute. :)

**Comment by NickColley** [comment]
Lol we both liking tidying I guess 😂

**Pull request closed without merging**
