### PR TITLE
[WIP] feat: click on curent column nav button to go to the top of the timeline

### PR DESCRIPTION
**Pull request by mlcdf**
I took the scroll.js file from the Mastodon codebase. I still need to add some tests (once I figure out how TestCafé works). 

Let me know what you think so far.

(related to #21)

### CODE REVIEW

**Comment by nolanlawson** [comment]
This looks great! :tada: I think I may need to tweak it to support some niche scenarios (e.g. pinning a list to the nav bar), but for the most part this looks great. I will give it a look over later tonight.

TestCafe has not been set up to run in Travis yet, but yes, long-term it'd be great to have TestCafe tests. :)

**Comment by nolanlawson** [comment]
I think the thing that may help move this PR along is, instead of checking the current `window.location`, to instead use `this.get('page')` to get the current page.

**Comment by mlcdf** [comment]
I'll look into this. Thanks!

**Comment by nolanlawson** [comment]
Sorry, couldn't resist getting this feature in. 😁 Merged it here: #69

**Comment by mlcdf** [comment]
No problem!

**Pull request closed without merging**
