### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by koyuawsmbrtn**
Note: A running Docker container must be killed instead of getting stopped. Ctrl-C/`SIGINT` doesn't seem to work while running Pinafore.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks, this seems reasonable to merge now. Is the `SIGINT` issue a big deal? I don't know anything about Docker.

**Comment by koyuawsmbrtn** [comment]
@nolanlawson admins just need to say `docker kill` instead of `docker stop`. This is not a big deal for now, yes.

**Comment by nolanlawson** [comment]
Should this be documented? Is there some way to fix it in `server.js`?

**Comment by koyuawsmbrtn** [comment]
It should be documented. Is there perhaps a handler, that fetches all keyboard interrupts or so?

**Comment by nolanlawson** [comment]
It's possible to add SIGINT interceptors in node. Here is [one example of how it might be done](https://github.com/pouchdb/pouchdb-server/blob/fdc6ba740190b5bc178a2f6665e91910e70df459/packages/node_modules/pouchdb-server/lib/index.js#L304-L306). What exactly is the desired behavior here? That SIGINT kills the process?

**Comment by koyuawsmbrtn** [comment]
This might do it. I'll try that.

**Comment by nolanlawson** [comment]
Awesome, thank you. The error seems to be an intermittent failure, so I'll restart until it passes and then merge.

**Comment by nolanlawson** [comment]
I don't understand why it's not passing. I'll keep looking into this.

**Comment by nolanlawson** [comment]
Thank you again!

**Pull request merged**
