### PR TITLE
Additional dark themes

### PR DESCRIPTION
**Pull request by pianycist**
I made three more dark themes based on the Sorcery theme: one with red as the base color, one with pink, and one with green.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Wow, these look amazing, thank you! Do you mind if I choose another name other than "dark pink" and "dark scarlet" though? I kinda like our current system where each theme has a single-word name.

Also: do you have a Mastodon/fediverse handle so I can credit you? :)

**Comment by pianycist** [comment]
Yes! Feel free to change the names. My main fediverse handle is metapianycist at queer.party.

**Comment by pianycist** [comment]
I'm thinking about "Punk" as the name for the dark theme with red?

**Comment by nolanlawson** [comment]
Awesome. Let's go with "Punk" for the dark red and "Riot" for the dark pink (makes me think of "riot grrl," so I guess I'm sticking with the punk theme :)).

**Comment by nolanlawson** [comment]
Merged as 9dac979cb6ca6d1e123044ff0604f0c04a0296b1 and 24dc3ad2aeb55901d95a90d5bb2078303686a4bb. Thanks very much!

**Pull request closed without merging**
