### PR TITLE
Add German locale

### PR DESCRIPTION
**Pull request by MarcoZehe**
This adds German as another UI language for Pinafore.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Awesome, thank you very much! FWIW there is also `emoji-picker/de.js` for translating the emoji picker, but as-is it will fall back to English for the emoji picker, no worries.

**Comment by nolanlawson** [comment]
Ah, you got it! Good timing. :)

**Comment by MarcoZehe** [comment]
Yes, and actually, the build will fail if that de.js for the Emoji picker isn't present. I just saw my first German language Pinafore. I'll have to correct a typo, but then I think it is ready to merge.

**Comment by nolanlawson** [comment]
@MarcoZehe Hey Marco, just to check, would you be okay with me adding the emoji picker translation directly to the `emoji-picker-element` project under a different license (Apache 2)?

**Comment by MarcoZehe** [comment]
Yes that's OK with me.

**Pull request merged**
