### PR TITLE
Make image use max-width and max-height in dialog

### PR DESCRIPTION
**Pull request by uiri**
Every time I click on an image to see the full version, it gets resized down to 300x200.

This PR fixes that :)

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks, although I think there was a reason I had to explicitly set the height/width. I'll play around with this and see how it works.

**Comment by nolanlawson** [comment]
Closing old issues, please reopen as necessary. Thanks!

**Comment by nolanlawson** [comment]
To be clear, I couldn't understand what this PR was tackling or any examples of images that didn't look right in the current CSS. It's possible there's something I missed with some particular kind of images in certain servers, though.

**Comment by uiri** [comment]
Hi, just adding a note here that it looks like the bug that I was observing has been fixed.

**Pull request closed without merging**
